// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using REVORA_BE.Models;

#nullable disable

namespace REVORA_BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("REVORA_BE.Models.AdminAuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("bigint");

                    b.HasKey("LogId");

                    b.HasIndex("AdminId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("REVORA_BE.Models.Announcement", b =>
                {
                    b.Property<long>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnnouncementId"));

                    b.Property<string>("BadgeText")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RedirectUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AnnouncementId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("REVORA_BE.Models.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BadgeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BadgeId");

                    b.ToTable("Badge");
                });

            modelBuilder.Entity("REVORA_BE.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("REVORA_BE.Models.Conversation", b =>
                {
                    b.Property<long>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ConversationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAtUser1")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAtUser2")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("User1Id")
                        .HasColumnType("bigint");

                    b.Property<long>("User2Id")
                        .HasColumnType("bigint");

                    b.HasKey("ConversationId");

                    b.HasIndex("User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("REVORA_BE.Models.CreditType", b =>
                {
                    b.Property<int>("CreditTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreditTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CreditTypeId");

                    b.ToTable("CreditTypes");
                });

            modelBuilder.Entity("REVORA_BE.Models.CreditUsageLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreditTypeId")
                        .HasColumnType("integer");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LogId");

                    b.HasIndex("CreditTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditUsageLogs");
                });

            modelBuilder.Entity("REVORA_BE.Models.Feedback", b =>
                {
                    b.Property<long>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FeedbackId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("REVORA_BE.Models.FreeCreditPackage", b =>
                {
                    b.Property<int>("FreeCreditPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FreeCreditPackageId"));

                    b.Property<int?>("BadgeDurationDays")
                        .HasColumnType("integer");

                    b.Property<int>("CreditAmount")
                        .HasColumnType("integer");

                    b.Property<int>("CreditTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RewardBadgeId")
                        .HasColumnType("integer");

                    b.HasKey("FreeCreditPackageId");

                    b.HasIndex("CreditTypeId");

                    b.HasIndex("RewardBadgeId");

                    b.ToTable("FreeCreditPackage");
                });

            modelBuilder.Entity("REVORA_BE.Models.MatchInterestNotification", b =>
                {
                    b.Property<long>("MatchInterestNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MatchInterestNotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("InterestedUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<long>("LikedProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("MatchSessionId")
                        .HasColumnType("bigint");

                    b.Property<long>("OfferingProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.HasKey("MatchInterestNotificationId");

                    b.HasIndex("InterestedUserId");

                    b.HasIndex("LikedProductId");

                    b.HasIndex("OfferingProductId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("MatchInterestNotifications");
                });

            modelBuilder.Entity("REVORA_BE.Models.MatchSession", b =>
                {
                    b.Property<long>("MatchSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MatchSessionId"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("MatchSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("MatchSessions");
                });

            modelBuilder.Entity("REVORA_BE.Models.MatchSessionProduct", b =>
                {
                    b.Property<long>("MatchSessionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("MatchSessionId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("MatchSessionProducts");
                });

            modelBuilder.Entity("REVORA_BE.Models.MatchSwipe", b =>
                {
                    b.Property<long>("MatchSwipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MatchSwipeId"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MatchSessionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SwipedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("TargetProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("MatchSwipeId");

                    b.HasIndex("TargetProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("MatchSessionId", "TargetProductId")
                        .IsUnique();

                    b.ToTable("MatchSwipes");
                });

            modelBuilder.Entity("REVORA_BE.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<long?>("ProductRefId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ProductRefId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("REVORA_BE.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("REVORA_BE.Models.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("CreditsGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PaidCreditPackageId")
                        .HasColumnType("integer");

                    b.Property<long>("PayOSOrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderTransactionId")
                        .HasColumnType("text");

                    b.Property<decimal?>("ReceivedAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("text");

                    b.Property<string>("ResponsePaymentContent")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("OrderId");

                    b.HasIndex("PaidCreditPackageId");

                    b.HasIndex("PayOSOrderCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("REVORA_BE.Models.PaidCreditPackage", b =>
                {
                    b.Property<int>("PaidCreditPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaidCreditPackageId"));

                    b.Property<int?>("BadgeDurationDays")
                        .HasColumnType("integer");

                    b.Property<int>("CreditAmount")
                        .HasColumnType("integer");

                    b.Property<int>("CreditTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("RewardBadgeId")
                        .HasColumnType("integer");

                    b.HasKey("PaidCreditPackageId");

                    b.HasIndex("CreditTypeId");

                    b.HasIndex("RewardBadgeId");

                    b.ToTable("PaidCreditPackage");
                });

            modelBuilder.Entity("REVORA_BE.Models.PaidCreditPackageDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("PaidCreditPackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaidCreditPackageId");

                    b.ToTable("PaidCreditPackageDescriptions");
                });

            modelBuilder.Entity("REVORA_BE.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("REVORA_BE.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProductId"));

                    b.Property<DateTime?>("BannerExpiredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("BannerStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HighlightExpiredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HighlightStatus")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMatchSeed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsedBanner")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsedShort")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("ProductCreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ProductExpiredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProductStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("REVORA_BE.Models.ProductComment", b =>
                {
                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CommentId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductComments");
                });

            modelBuilder.Entity("REVORA_BE.Models.ProductCommentLike", b =>
                {
                    b.Property<long>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductCommentLikes");
                });

            modelBuilder.Entity("REVORA_BE.Models.ProductImage", b =>
                {
                    b.Property<long>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProductImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("REVORA_BE.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("REVORA_BE.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("REVORA_BE.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("REVORA_BE.Models.Short", b =>
                {
                    b.Property<long>("ShortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ShortId"));

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShortId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("Shorts");
                });

            modelBuilder.Entity("REVORA_BE.Models.ShortComment", b =>
                {
                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShortId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CommentId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ShortId");

                    b.HasIndex("UserId");

                    b.ToTable("ShortComments");
                });

            modelBuilder.Entity("REVORA_BE.Models.ShortCommentLike", b =>
                {
                    b.Property<long>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ShortCommentLikes");
                });

            modelBuilder.Entity("REVORA_BE.Models.ShortLike", b =>
                {
                    b.Property<long>("ShortId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ShortId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ShortLikes");
                });

            modelBuilder.Entity("REVORA_BE.Models.TradeMatch", b =>
                {
                    b.Property<long>("TradeMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TradeMatchId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HighUserConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("HighUserNegotiateConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("HighUserSelectedProductIds")
                        .HasColumnType("text");

                    b.Property<bool>("LowUserConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LowUserNegotiateConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("LowUserSelectedProductIds")
                        .HasColumnType("text");

                    b.Property<long?>("ProductHighUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductLowUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("SessionHighUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("SessionLowUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserHighId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserLowId")
                        .HasColumnType("bigint");

                    b.HasKey("TradeMatchId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ProductHighUserId");

                    b.HasIndex("ProductLowUserId");

                    b.HasIndex("UserHighId");

                    b.HasIndex("UserLowId", "UserHighId", "Status");

                    b.ToTable("TradeMatches");
                });

            modelBuilder.Entity("REVORA_BE.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<int?>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFirstLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("TradeSuccessCount")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("REVORA_BE.Models.UserBadge", b =>
                {
                    b.Property<int>("UserBadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserBadgeId"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserBadgeId");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBadge");
                });

            modelBuilder.Entity("REVORA_BE.Models.UserCreditBatch", b =>
                {
                    b.Property<long>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BatchId"));

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreditTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FreePackageId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PaidPackageId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RemainingCredits")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("BatchId");

                    b.HasIndex("CreditTypeId");

                    b.HasIndex("FreePackageId");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("\"OrderId\" IS NOT NULL");

                    b.HasIndex("PaidPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCreditBatches");
                });

            modelBuilder.Entity("REVORA_BE.Models.UserFollow", b =>
                {
                    b.Property<long>("FollowerId")
                        .HasColumnType("bigint");

                    b.Property<long>("FolloweeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("FollowerId", "FolloweeId");

                    b.HasIndex("FolloweeId");

                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("REVORA_BE.Models.Wishlist", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("REVORA_BE.Models.AdminAuditLog", b =>
                {
                    b.HasOne("REVORA_BE.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("REVORA_BE.Models.Conversation", b =>
                {
                    b.HasOne("REVORA_BE.Models.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("REVORA_BE.Models.CreditUsageLog", b =>
                {
                    b.HasOne("REVORA_BE.Models.CreditType", "CreditType")
                        .WithMany()
                        .HasForeignKey("CreditTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreditType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.Feedback", b =>
                {
                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.FreeCreditPackage", b =>
                {
                    b.HasOne("REVORA_BE.Models.CreditType", "CreditType")
                        .WithMany("FreeCreditPackages")
                        .HasForeignKey("CreditTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.Badge", "RewardBadge")
                        .WithMany()
                        .HasForeignKey("RewardBadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreditType");

                    b.Navigation("RewardBadge");
                });

            modelBuilder.Entity("REVORA_BE.Models.MatchInterestNotification", b =>
                {
                    b.HasOne("REVORA_BE.Models.User", "InterestedUser")
                        .WithMany()
                        .HasForeignKey("InterestedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.Product", "LikedProduct")
                        .WithMany()
                        .HasForeignKey("LikedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.Product", "OfferingProduct")
                        .WithMany()
                        .HasForeignKey("OfferingProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterestedUser");

                    b.Navigation("LikedProduct");

                    b.Navigation("OfferingProduct");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("REVORA_BE.Models.MatchSession", b =>
                {
                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.MatchSessionProduct", b =>
                {
                    b.HasOne("REVORA_BE.Models.MatchSession", "MatchSession")
                        .WithMany("OfferingProducts")
                        .HasForeignKey("MatchSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchSession");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("REVORA_BE.Models.MatchSwipe", b =>
                {
                    b.HasOne("REVORA_BE.Models.MatchSession", "MatchSession")
                        .WithMany("Swipes")
                        .HasForeignKey("MatchSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.Product", "TargetProduct")
                        .WithMany()
                        .HasForeignKey("TargetProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchSession");

                    b.Navigation("TargetProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.Message", b =>
                {
                    b.HasOne("REVORA_BE.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.Product", "ProductRef")
                        .WithMany()
                        .HasForeignKey("ProductRefId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("REVORA_BE.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("ProductRef");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("REVORA_BE.Models.Notification", b =>
                {
                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.Order", b =>
                {
                    b.HasOne("REVORA_BE.Models.PaidCreditPackage", "PaidCreditPackage")
                        .WithMany("Orders")
                        .HasForeignKey("PaidCreditPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaidCreditPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.PaidCreditPackage", b =>
                {
                    b.HasOne("REVORA_BE.Models.CreditType", "CreditType")
                        .WithMany("PaidCreditPackages")
                        .HasForeignKey("CreditTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.Badge", "RewardBadge")
                        .WithMany()
                        .HasForeignKey("RewardBadgeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreditType");

                    b.Navigation("RewardBadge");
                });

            modelBuilder.Entity("REVORA_BE.Models.PaidCreditPackageDescription", b =>
                {
                    b.HasOne("REVORA_BE.Models.PaidCreditPackage", "PaidCreditPackage")
                        .WithMany("Descriptions")
                        .HasForeignKey("PaidCreditPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaidCreditPackage");
                });

            modelBuilder.Entity("REVORA_BE.Models.Product", b =>
                {
                    b.HasOne("REVORA_BE.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("REVORA_BE.Models.ProductComment", b =>
                {
                    b.HasOne("REVORA_BE.Models.ProductComment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("REVORA_BE.Models.Product", "Product")
                        .WithMany("ProductComments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany("ProductComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.ProductCommentLike", b =>
                {
                    b.HasOne("REVORA_BE.Models.ProductComment", "ProductComment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany("ProductCommentLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.ProductImage", b =>
                {
                    b.HasOne("REVORA_BE.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("REVORA_BE.Models.RefreshToken", b =>
                {
                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.RolePermission", b =>
                {
                    b.HasOne("REVORA_BE.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("REVORA_BE.Models.Short", b =>
                {
                    b.HasOne("REVORA_BE.Models.Product", "Product")
                        .WithMany("Shorts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("REVORA_BE.Models.User", "Seller")
                        .WithMany("Shorts")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("REVORA_BE.Models.ShortComment", b =>
                {
                    b.HasOne("REVORA_BE.Models.ShortComment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("REVORA_BE.Models.Short", "Short")
                        .WithMany("ShortComments")
                        .HasForeignKey("ShortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany("ShortComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Short");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.ShortCommentLike", b =>
                {
                    b.HasOne("REVORA_BE.Models.ShortComment", "ShortComment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShortComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.ShortLike", b =>
                {
                    b.HasOne("REVORA_BE.Models.Short", "Short")
                        .WithMany("ShortLikes")
                        .HasForeignKey("ShortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany("ShortLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Short");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.TradeMatch", b =>
                {
                    b.HasOne("REVORA_BE.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("REVORA_BE.Models.Product", "ProductHighUser")
                        .WithMany()
                        .HasForeignKey("ProductHighUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("REVORA_BE.Models.Product", "ProductLowUser")
                        .WithMany()
                        .HasForeignKey("ProductLowUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("REVORA_BE.Models.User", "UserHigh")
                        .WithMany()
                        .HasForeignKey("UserHighId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "UserLow")
                        .WithMany()
                        .HasForeignKey("UserLowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("ProductHighUser");

                    b.Navigation("ProductLowUser");

                    b.Navigation("UserHigh");

                    b.Navigation("UserLow");
                });

            modelBuilder.Entity("REVORA_BE.Models.User", b =>
                {
                    b.HasOne("REVORA_BE.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("REVORA_BE.Models.UserBadge", b =>
                {
                    b.HasOne("REVORA_BE.Models.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.UserCreditBatch", b =>
                {
                    b.HasOne("REVORA_BE.Models.CreditType", "CreditType")
                        .WithMany("UserCreditBatches")
                        .HasForeignKey("CreditTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.FreeCreditPackage", "FreeCreditPackage")
                        .WithMany()
                        .HasForeignKey("FreePackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("REVORA_BE.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("REVORA_BE.Models.PaidCreditPackage", "PaidCreditPackage")
                        .WithMany("UserCreditBatches")
                        .HasForeignKey("PaidPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany("UserCreditBatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreditType");

                    b.Navigation("FreeCreditPackage");

                    b.Navigation("Order");

                    b.Navigation("PaidCreditPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.UserFollow", b =>
                {
                    b.HasOne("REVORA_BE.Models.User", "Followee")
                        .WithMany("Followers")
                        .HasForeignKey("FolloweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "Follower")
                        .WithMany("Followees")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("REVORA_BE.Models.Wishlist", b =>
                {
                    b.HasOne("REVORA_BE.Models.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REVORA_BE.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("REVORA_BE.Models.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("REVORA_BE.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("REVORA_BE.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("REVORA_BE.Models.CreditType", b =>
                {
                    b.Navigation("FreeCreditPackages");

                    b.Navigation("PaidCreditPackages");

                    b.Navigation("UserCreditBatches");
                });

            modelBuilder.Entity("REVORA_BE.Models.MatchSession", b =>
                {
                    b.Navigation("OfferingProducts");

                    b.Navigation("Swipes");
                });

            modelBuilder.Entity("REVORA_BE.Models.PaidCreditPackage", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("Orders");

                    b.Navigation("UserCreditBatches");
                });

            modelBuilder.Entity("REVORA_BE.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("REVORA_BE.Models.Product", b =>
                {
                    b.Navigation("ProductComments");

                    b.Navigation("ProductImages");

                    b.Navigation("Shorts");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("REVORA_BE.Models.ProductComment", b =>
                {
                    b.Navigation("ChildComments");

                    b.Navigation("CommentLikes");
                });

            modelBuilder.Entity("REVORA_BE.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("REVORA_BE.Models.Short", b =>
                {
                    b.Navigation("ShortComments");

                    b.Navigation("ShortLikes");
                });

            modelBuilder.Entity("REVORA_BE.Models.ShortComment", b =>
                {
                    b.Navigation("ChildComments");
                });

            modelBuilder.Entity("REVORA_BE.Models.User", b =>
                {
                    b.Navigation("Followees");

                    b.Navigation("Followers");

                    b.Navigation("Orders");

                    b.Navigation("ProductCommentLikes");

                    b.Navigation("ProductComments");

                    b.Navigation("Products");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ShortComments");

                    b.Navigation("ShortLikes");

                    b.Navigation("Shorts");

                    b.Navigation("UserBadges");

                    b.Navigation("UserCreditBatches");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
